language: ruby

rvm:
  - 2.3.1

services:
    - postgresql

env:
    POSTGRES_HOST: localhost
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: 
    POSTGRES_PORT: 5432

install:
    - bundle install
    - rake bower:install db:create db:migrate

script:
    - rake test jasmine:ci

